### ISSUE TITLE
For more security spongycastle -> bouncycastle

### ISSUE THREAD

**Issue by Neustradamus** [UniversaBlockchain/web3j#1]
For more security, can you change old spongycastle (based on old bouncycastle) to bouncycastle?
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncy%20castle
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncycastle
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by amyodov** [comment]
“Spongycastle vs Bouncycastle” decision is mostly decided by upstream web3j dependencies; and our web3j version used internally is based on rather old upstream-web3j, which still depends on spongycastle.

Rebasing our web3j fork from 3.3.1 right to 4.5.17 (which is the current upstream web3j version) is far from a piece of cake. We will do that eventually, refactoring the web3j usage internally (and it is in progress, actually, _these days_), getting rid of some of our web3j tweaks and leaving only still-important ones. In particular:

- We still need to double-check if the upstream version has received any better timeout/reconnect handling, so we probably can already get rid of our custom patches to rebuild the connections; but in fact, our internal workflow may change to get rid of notification subscriptions completely, and we may just abandon this part.
- Ethereum Classic supporting patch (txpool_content) – it is tiny and it may likely can be ported easily.
- A patch to get the tx id promptly, right on sending the transaction (rather than on it being mined) – will definitely survive, as it is so important; but I really hope such a feature has been (or will be) somehow implemented upstream already (cause having no so important functionality is weird, maybe I just overlooked it somehow).

As a part of this refactoring process, upgrading to later web3j will shift the underlying crypto lib to bouncycastle, indeed (all our internal codebase has migrated to bouncycastle already), but I cannot give any milestones on it. Luckily, it is used in strictly controlled internal environment exclusively.

**Comment by Neustradamus** [comment]
@amyodov: Thanks for your comment!
I have already done a ticket to main repository :)

**Comment by amyodov** [comment]
https://github.com/web3j/web3j/issues/1184 , I see. 

Interestingly I double-checked and I don't see if web3j still uses spongycastle anywhere directly. Neither upstream version, nor even our fork.

**Comment by amyodov** [comment]
I just realized you added this ticket to multiple projects – thanks for your vigilancy!
Will check them all, and close the ticket whenever it seems inapplicable at the moment. Feel free to reopen if find it problematic.
